# Generated by Django 5.2.7 on 2025-10-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tag'], name='core_note_tag_0f934c_idx'),
        ),
    ]
